-- supabase/migrations/20250618110000_create_proposals_table.sql (Passenden Zeitstempel wählen!)
CREATE TABLE public.proposals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    category text NOT NULL,
    name text NOT NULL,
    price numeric NOT NULL,
    image_url text NULL,
    description text NULL,
    status text DEFAULT 'pending' NOT NULL,
    user_id uuid NOT NULL
);

ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert proposals" ON public.proposals
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow authenticated users to view their own proposals" ON public.proposals
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow all authenticated users to view approved or completed proposals" ON public.proposals
FOR SELECT USING (status = 'approved' OR status = 'completed');

-- Optional: Policy für Benutzer, um ihre eigenen PENDING-Vorschläge zu aktualisieren
CREATE POLICY "Allow authenticated users to update their own pending proposals" ON public.proposals
FOR UPDATE USING (auth.uid() = user_id AND status = 'pending') WITH CHECK (true);

-- Optional: Policy für Benutzer, um ihre eigenen PENDING-Vorschläge zu löschen
CREATE POLICY "Allow authenticated users to delete their own pending proposals" ON public.proposals
FOR DELETE USING (auth.uid() = user_id AND status = 'pending');